//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bag
    {
        public int order_ID { get; set; }
        public int tea_ID { get; set; }
        public Nullable<int> count { get; set; }
        public int bag_ID { get; set; }
    
        public virtual order order { get; set; }
        public virtual tea tea { get; set; }
    }
}
