//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModFirm.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;


    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Orders = new HashSet<Order>();
        }
        public string GetPhoto
        {
            get
            {
                if (Image is null || Image == "")
                    return Directory.GetCurrentDirectory() + @"\Images\" + "Default.jpg";
                return Directory.GetCurrentDirectory() + @"\Images\" + Image.Trim();
            }
        }
        public int Employee_ID { get; set; }
        public int Post_ID { get; set; }
        public string Birth { get; set; }
        public string Mail { get; set; }
        public string Number { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Second_Name { get; set; }
        public int Pass_Ser { get; set; }
        public int Pass_Num { get; set; }
        public string Image { get; set; }
    
        public virtual Post Post { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
