//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TeaShopEntities : DbContext
    {
        public TeaShopEntities()
            : base("name=TeaShopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        private static TeaShopEntities _context;
        public static TeaShopEntities GetContext()
        {
            if (_context == null)
            {
                _context = new TeaShopEntities();
            }
            return _context;
        }
        public virtual DbSet<bag> bags { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<delivery> deliveries { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<post> posts { get; set; }
        public virtual DbSet<provider> providers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tea> teas { get; set; }
        public virtual DbSet<type> types { get; set; }
        public virtual DbSet<user> users { get; set; }
    }
}
