//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public order()
        {
            this.bags = new HashSet<bag>();
        }
    
        public int order_ID { get; set; }
        public int customer_ID { get; set; }
        public Nullable<int> delivery_ID { get; set; }
        public string customer_address { get; set; }
        public Nullable<System.DateTime> date_order { get; set; }
        public Nullable<double> price_order { get; set; }
        public int employee_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bag> bags { get; set; }
        public virtual customer customer { get; set; }
        public virtual delivery delivery { get; set; }
        public virtual employee employee { get; set; }
    }
}
