//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModFirm.Models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Order_Product = new HashSet<Order_Product>();
        }
        public string GetPhoto
        {
            get
            {
                if (Image is null || Image == "")
                    return Directory.GetCurrentDirectory() + @"\Images\" + "Default.jpg";
                return Directory.GetCurrentDirectory() + @"\Images\" + Image.Trim();
            }
        }
        public int Product_ID { get; set; }
        public int Category_ID { get; set; }
        public int Purpose_ID { get; set; }
        public string Image { get; set; }
        public string Product_name { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_Product> Order_Product { get; set; }
        public virtual Purpose Purpose { get; set; }
    }
}
