//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeaShop.models
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    
    public partial class tea
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tea()
        {
            this.bags = new HashSet<bag>();
        }
        public string GetPhoto
        {
            get
            {
                if (image is null)
                    return null;
                return Directory.GetCurrentDirectory() + @"\Images\" + image.Trim();
            }
        }
        public int tea_ID { get; set; }
        public string name { get; set; }
        public int type_ID { get; set; }
        public double price { get; set; }
        public string image { get; set; }
        public string description { get; set; }
        public int provider_ID { get; set; }
        public Nullable<int> count { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<bag> bags { get; set; }
        public virtual provider provider { get; set; }
        public virtual type type { get; set; }
    }
}
