//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModFirm.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int Auth_ID { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int Role_ID { get; set; }
        public Nullable<int> Client_ID { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Role Role { get; set; }
    }
}
